--Q1) HOW MANY RESTAURANTS HAVE A RATING GREATER THAN 4.5?

SELECT COUNT(DISTINCT RESTAURANT_NAME) FROM SWIGGY WHERE RATING >4.5;


--Q2) WHICH IS THE TOP 1 CITY WITH THE HIGHEST NUMBER OF RESTAURANTS?

SELECT CITY, COUNT(DISTINCT RESTAURANT_NAME) AS REST_COUNT FROM SWIGGY 
GROUP BY CITY 
ORDER BY 2 DESC LIMIT 1;


--Q3) HOW MANY RESTAURANTS HAVE THE WORD "PIZZA" IN THEIR NAME?

SELECT DISTINCT RESTAURANT_NAME AS REST_COUNT FROM SWIGGY 
WHERE RESTAURANT_NAME LIKE '%PIZZA%';


--Q4) WHAT IS THE MOST COMMON CUISINE AMONG THE RESTAURANTS IN THE DATASET?

SELECT CUISINE, COUNT(*) AS CUISINE_COUNT
FROM SWIGGY
GROUP BY CUISINE
ORDER BY CUISINE_COUNT DESC LIMIT 1;


--Q5) WHAT IS THE AVERAGE RATING OF RESTAURANTS IN EACH CITY?

SELECT AVG(RATING) FROM SWIGGY GROUP BY CITY;


--Q6) WHAT IS THE HIGHEST PRICE OF ITEM UNDER THE 'RECOMMENDED' MENU CATEGORY FOR EACH RESTAURANT?

SELECT DISTINCT RESTAURANT_NAME, MENU_CATEGORY ,MAX(PRICE) AS HIGHEST_PRICE 
FROM SWIGGY
WHERE MENU_CATEGORY ='RECOMMENDED'
GROUP BY RESTAURANT_NAME, MENU_CATEGORY;


--Q7) FIND THE TOP 5 MOST EXPENSIVE RESTAURANTS THAT OFFER CUISINE OTHER THAN INDIAN CUISINE

SELECT DISTINCT RESTAURANT_NAME, COST_PER_PERSON FROM SWIGGY
WHERE CUISINE <>'INDIAN'
ORDER BY 2 DESC LIMIT 5;


--Q8) FIND THE RESTAURANTS THAT HAVE AN AVERAGE COST WHICH IS HIGHER THAN THE TOTAL AVERAGE COST OF ALL RESTAURANTS TOGETHER.

SELECT DISTINCT RESTAURANT_NAME, COST_PER_PERSON 
FROM SWIGGY 
WHERE COST_PER_PERSON>(SELECT AVG(COST_PER_PERSON) FROM SWIGGY);


--Q9) RETRIEVE THE DETAILS OF RESTAURANTS THAT HAVE THE SAME NAME BUT ARE LOCATED IN DIFFERENT CITIES.

SELECT DISTINCT T1.RESTAURANT_NAME, T1.CITY, T2.CITY 
FROM SWIGGY T1 JOIN SWIGGY T2 
ON T1.RESTAURANT_NAME = T2.RESTAURANT_NAME AND T1.CITY <> T2.CITY;


--Q10) WHICH RESTAURANT OFFERS THE MOST NUMBER OF ITEMS IN THE 'MAIN COURSE' CATEGORY?

SELECT DISTINCT RESTAURANT_NAME, MENU_CATEGORY, COUNT(ITEM) AS NO_OF_ITEMS 
FROM SWIGGY 
WHERE MENU_CATEGORY = 'MAIN COURSE' 
GROUP BY RESTAURANT_NAME, MENU_CATEGORY
ORDER BY 3 DESC LIMIT 1;


--Q11) LIST THE NAMES OF RESTAURANTS THAT ARE 100% VEGEATARIAN IN ALPHABETICAL ORDER OF RESTAURANT NAME

SELECT DISTINCT RESTAURANT_NAME, 
(COUNT(CASE 
            WHEN VEG_OR_NONVEG='VEG' 
            THEN 1 
            END)*100/COUNT(*)) AS VEGETARIAN_PERCENTAGE 
FROM SWIGGY
GROUP BY RESTAURANT_NAME HAVING VEGETARIAN_PERCENTAGE=100.00 
ORDER BY RESTAURANT_NAME;


--Q12) WHICH IS THE RESTAURANT PROVIDING THE LOWEST AVERAGE PRICE FOR ALL ITEMS?

SELECT DISTINCT RESTAURANT_NAME, AVG(PRICE) AS AVG_PRICE 
FROM SWIGGY
GROUP BY RESTAURANT_NAME
ORDER BY AVG_PRICE LIMIT 1;


--Q13) WHICH TOP 5 RESTAURANT OFFERS HIGHEST NUMBER OF CATEGORIES?

SELECT DISTINCT RESTAURANT_NAME, COUNT(DISTINCT MENU_CATEGORY) AS NO_OF_CATEGORIES
FROM SWIGGY
GROUP BY RESTAURANT_NAME
ORDER BY NO_OF_CATEGORIES DESC
LIMIT 5;


--Q14) WHICH RESTAURANT PROVIDES THE HIGHEST PERCENTAGE OF NON-VEGEATARIAN FOOD?

SELECT DISTINCT RESTAURANT_NAME, 
(COUNT(CASE
            WHEN VEG_OR_NONVEG='NON-VEG'
            THEN 1 
            END)*100/COUNT(*)) AS NON_VEGETARIAN_PERCENTAGE
FROM SWIGGY
GROUP BY RESTAURANT_NAME
ORDER BY NON_VEGETARIAN_PERCENTAGE DESC LIMIT 1;
